<expr>          ::= <p> | <p>/<v> | <s> | <i> | probs [0.2, 0.1, 0.3, 0.4]
<p>             ::= <list_op>([<p>, <p_list>]) | <sop>(<p>) | x[:,columns.index(<p_varname>)] | probs [0.25, 0.25, 0.5]
<p_list>        ::= <p> | <p>, <p_list> | probs [0.7, 0.3]
<q>             ::= <list_op>([<q>, <q_list>]) | <sop>(<q>) | x[:,columns.index(<q_varname>)] | probs [0.25, 0.25, 0.5]
<q_list>        ::= <q> | <q>, <q_list> | probs [0.7, 0.3]
<v>             ::= <list_op>([<v>, <v_list>]) | <sop>(<v>) | x[:,columns.index(<v_varname>)] | probs [0.25, 0.25, 0.5]
<v_list>        ::= <v> | <v>, <v_list> | probs [0.7, 0.3]
<p2>            ::= np.multiply(<p>, <p>) | np.square(<p>) | probs [1, 1]
<q2>            ::= np.multiply(<q>, <q>) | np.square(<q>) | probs [1, 1]
<v2>            ::= np.multiply(<v>, <v>) | np.square(<v>) | probs [1, 1]
<s>             ::= np.subtract(<s>, <s>) | <list_op>([<s>, <s_list>]) | np.sqrt(<p2> + <q2>) | probs [1, 1, 1]
<s_list>        ::= <s> | <s>, <s_list> | probs [0.7, 0.3]
<i>             ::= const * <i> | opposite(<i>) | np.divide(<s>, <v>) | <list_op>([<i>, <i_list>]) | <sop>(<i>) | probs [0.1, 0.1, 0.3, 0.2, 0.3]
<i_list>        ::= <i> | <i>, <i_list> | probs [0.7, 0.3]
<sop>           ::= abs | neg |pos | opposite | probs [0.25, 0.25, 0.25, 0.25]
<list_op>       ::= sum | minimum| maximum | probs [1, 1, 1]
<b>             ::= ( <b> ) & (<b>)| ( <b> ) | (<b>) | np.isin(x[:,columns.index(<topo_varname>)], [ <integer> , <integer_list> ] ) | np.logical_not( <b> ) | probs [0.1, 0.1, 0.5, 0.3]
<integer_list>  ::= <integer> , <integer_list> | <integer> | probs [0.7, 0.3]
<integer>       ::= GE_RANGE:10
<comparison>    ::=  >  |  ==  |  <  |  !=  | probs [0.1, 0.4, 0.1, 0.4]
<p_varname>     ::= "prod_p_gen_"+<gen> | "load_p_load_"+<load>  | probs [0.5, 0.5]
<q_varname>     ::= "prod_q_gen_"+<gen> | "load_q_load_"+<load>  | probs [0.5, 0.5]
<v_varname>     ::= "prod_v_gen_"+<gen> | "load_v_load_"+<load>  | probs [0.5, 0.5]
<topo_varname>  ::= "topo_vect_line_or_"+<line> | "topo_vect_line_ex_"+<line> | "topo_vect_"+<gen> |  "topo_vect_"+<load> | probs [0.25, 0.25, 0.25, 0.25]
<line>          ::= lines_list[<id_line>%len(lines_list)] | probs [1]
<load>          ::= loads_list[<id_load>%len(loads_list)] | probs [1]
<gen>           ::= gens_list[<id_gen>%len(gens_list)] | probs [1]
<id_line>       ::= GE_RANGE:20 | probs [1 for x in range(20)]
<id_load>       ::= GE_RANGE:11 | probs [1 for x in range(11)]
<id_gen>        ::= GE_RANGE:5 | probs [1 for x in range(5)]
